### ISSUE TITLE
Failure on last Test Vector

### ISSUE THREAD

**Issue by SymmetricChaos** [khonsulabs/cityhasher#1]
The test suite uses this code
```
#[test]
fn suite() {
    let data = setup();
    for i in 0..TEST_COUNT - 1 {
        let offset = i * i;
        test(&TESTDATA[i], &data[offset..offset + i]);
    }
}
```
That only checks the first 299 of the 300 test vectors. When I modify the code to include the last test vector it fails for just that one. The same is true of my own implementation (https://github.com/SymmetricChaos/crypto-gui/tree/master/hashers/src/cityhash) and the Go implementation I referenced to make it (https://github.com/creachadair/cityhash/blob/v0.1.1/cityhash.go)

Do you have any idea what causes this? It seems to me that the outputs for the last test are wrong since all of these implementation not only fail but do so with the same result: 0x48C31271.

**Comment by ecton** [comment]
I don't believe this is a bug. The original test suite is [this](https://github.com/google/cityhash/blob/master/src/city-test.cc#L1327C1-L1335C2):

```c
int main(int argc, char** argv) {
  setup();
  int i = 0;
  for ( ; i < kTestSize - 1; i++) {
    Test(testdata[i], i * i, i);
  }
  Test(testdata[i], 0, kDataSize);
  return errors > 0;
}
```

The loop will run while `i` is less than `kTestSize - 1`. This means the upper bound of the iteration is 298. So, if this is indeed a bug, it exists in the original C code as well.

I noticed the original test code has one final test with i being 299 since that's the condition it exits the loop, and I added that [this morning](https://github.com/khonsulabs/cityhasher/commit/cb1f7723ca525224d3fa0796223b173e428fb10e#diff-a0262fea108af44a98cc49e5eb72641963dd816513f2d0a22eb738fcfed55ebeR18) to my implementation, and it passes as well. I'm very confident my implementation matches the C implementation.
